### ISSUE TITLE
Can be imported as `reconciler.io/dies`

### ISSUE THREAD

**Issue by mamachanko** [reconcilerio/dies#133]
Dies cannot be imported as `reconciler.io/dies` yet:

```
❯ go mod init github.com/mamachanko/use-dies
go: creating new go.mod: module github.com/mamachanko/use-dies

❯ go get reconciler.io/dies
go: unrecognized import path "reconciler.io/dies": parse https://reconciler.io/dies?go-get=1: no go-import meta tags (meta tag reconciler.io/runtime did not match import path reconciler.io/dies, meta tag dies.dev did not match import path reconciler.io/dies)
```

We should follow-up with a change similar to 
https://github.com/reconcilerio/runtime/releases/tag/v0.20.0 which adjusts the import path etc.

**Comment by scothis** [comment]
No change is required as dies.dev continues to work.

**Comment by mamachanko** [comment]
Yes, but I thought - and I might be mistaken here - that there could be consistent "branding" across reconcilerio's projects when there import path share the top-level `reconciler.io`, wouldn't you think?

**Comment by scothis** [comment]
We certainly could, but it would force all users to migrate to a longer package name. For runtime, the name change was unavoidable since it used the vmware-labs GitHub org as the name.

**Comment by mamachanko** [comment]
I understand! 👍🏻 

Let's keep this open as to consider it eventually, unless you rule it out categorically.

**Comment by scothis** [comment]
Not ruling it out, as I do like symmetry.

**Comment by mamachanko** [comment]
```
❯ mkdir tmp

❯ cd tmp

❯ go mod init github.com/mamachanko/use-dies
go: creating new go.mod: module github.com/mamachanko/use-dies

❯ go get reconciler.io/dies
go: downloading reconciler.io/dies v0.11.0
go: added reconciler.io/dies v0.11.0
```

🎉
