### ISSUE TITLE
diegen Panics When Encountering a Generated File

### ISSUE THREAD

**Issue by nebhale** [reconcilerio/dies#143]
Currently, when running `digen` on a project with paths set to `./...` I experience a panic when it reaches a file containing
```
//go:build !ignore_autogenerated
// +build !ignore_autogenerated 
```

An example of the panic is listed below.

```
...
Generating field "Conditions" for "APIExportStatus"
Generating field "VirtualWorkspaces" for "APIExportStatus"
-: build constraints exclude all Go files in /go/pkg/mod/github.com/kcp-dev/client-go@v0.0.0-20240515123258-607e9d833b0e/kubernetes/scheme
panic: true

goroutine 1 [running]:
main.main()
	/go/pkg/mod/reconciler.io/dies/diegen@v0.12.0/main.go:45 +0x100
exit status 2
```

What is unclear to me is why this file even being scanned for generation in the first place.  Specifically, this is a go module, not. my primary code, and the only reference to that package is an import statement in one of my go files.  I'd have expected the traversal of files to end in my code base.  In the absence of that behavior, I'd expect a directory only containing ignore build constraints not to cause a panic.

**Comment by scothis** [comment]
I'm not sure why it would descend into a dependent module. I've never seen that behavior. Can you reproduce this with diegen@v0.11.0? One of the changes in v0.12 was updating controller-tools.

**Comment by nebhale** [comment]
In fact a change to my `go.mod` seems to have made it go away with v0.12.  My guess is that there was some very screwy dependency tree going on (forks of various projects trying to co-exist).  I'm happy to close this for now and re-open if I see it again.
